### ISSUE TITLE
Roadmap of elements to check

### ISSUE THREAD

**Issue by Bisaloo** [Bisaloo/cran-task-view-analysis#2]
## Adherence to modern good practices in software development

- [x] Presence of automated tests, as indicated by the presence of a testing framework package in `Suggests`: c("testthat", "testit", "unitizer", "RUnit", “tinytest”)
- [x] Package hosted on GitHub
- [x] Presence of a README
- [ ] Presence of a Code of Conduct and/or a Contributing guide (can be detected via GitHub API if the package is hosted on GitHub, or if `.Rbuildignore` contains `^CODE_OF_CONDUCT\.md$`): in #30 
- [x] The packages don’t rely on an obsolete dependency ([as defined by rOpenSci](https://devguide.ropensci.org/building.html#recommended-scaffolding))
- [x] Use of continuous integration, as signaled by the presence of relevant badges in the README

## Release cadence and sustained maintenance
- Summary statistics of:
  - [ ] Number of updates
  - [ ] Time elapsed between two successive updates
- [ ] Date of last update

## If hosted on GitHub, number of contributors

- ~~Interest in the package~~
- [x] Number of downloads over time
- [x] Number of stars in GitHub
